### PR TITLE
hainputslider

### PR DESCRIPTION
**Pull request by ReneTode**
I hope this works.
this is my first pull request, and i hope i have remembered all changes i made correctly.

### CODE REVIEW

**Comment by acockburn** [comment]
This looks great Rene - thanks. Could you maybe add some guidance to the docs as well please?

**Comment by ReneTode** [comment]
i love to if i would know where to find it in the moment.
let me try to find that out tommorow. when i dont find it tommorow it will be next week ;)

**Comment by ReneTode** [comment]
hmm, am i correct that the docs are on homeassistant now?
because i didnt fork that because i have 0.28.2 running and not the latest version.
and i didnt want to fork something i am not using. (or at least that is what i think that would mean)

can i add/change/ make a pull request/ anything when i dont fork the latest version?
and how?

**Comment by Danielhiversen** [comment]
@acockburn Any plan to merge this soon?
I hope to start using this feature soon.

**Comment by acockburn** [comment]
I have been focusing on AppDaemon recently, I am planning to have a push on HADashboard soon.

**Comment by acockburn** [comment]
I will not be merging this however I will add equivalent functionality to HADashboard v2.

**Pull request closed without merging**
