### PR TITLE
Migrate from Hagarage > Hacover

### PR DESCRIPTION
**Pull request by jwl17330536**
I didn't do this cleanly.. again!  The descriptions are all over the place.

My intention was modify hapush and remove "garage_door" with "cover" and "Hagarage" > "Hacover".

I also moved the files from widgets/hagarage > widgets/hacover.  All those files should also have all references to garage changed to cover.  

Lastly, I modified the README file to reference cover rather than garage.

### CODE REVIEW

**Comment by acockburn** [comment]
Thanks for this - I just implemented the same functionality myself today ironically. I decided to add Hacover, but leave garage intact to avoid breaking anyone's existing dashboards. I will test a little more tomorrow then release it.

**Comment by jwl17330536** [comment]
I'm going to close this for now then.  Would you rather push yours?  I actually liked that idea better, but chose to go this way because I figured you would like it better this way!

**Comment by acockburn** [comment]
Yes, would be easier to stick with mine I think, but I appreciate your efforts :) I'll credit you in the release notes for this even though I didn't us it.

**Comment by jwl17330536** [comment]
No need!

**Pull request closed without merging**
